version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=zsfq@q18aq#o%8)e^qj1#!+2^x
      - DEBUG=1
